# npm-check-updates configuration used by pnpm deps:check && pnpm deps:update
# convenience scripts.
# @link https://github.com/raineorshine/npm-check-updates

# Add here exclusions on packages if any
reject: []