name: ReleaseOrVersionPR

on:
  push:
    branches: [main]

jobs:
  release:
    name: Release and changelog
    runs-on: ubuntu-latest
    # Basic security: the release job can only be executed from this repo and from the main branch
    if: ${{ github.repository == 'udecode/plate' && contains('refs/heads/main',github.ref)}}

    steps:
      - name: üì• Checkout Repo
        uses: actions/checkout@v4
        with:
          # To run comparison we need more than the latest commit
          fetch-depth: 0

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: ‚ôªÔ∏è Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: ‚ôªÔ∏è Setup bun cache
        uses: actions/cache@v4
        with:
          path: ~/.bun/install/cache
          key: ${{ runner.os }}-bun-${{ hashFiles('**/bun.lock') }}
          restore-keys: |
            ${{ runner.os }}-bun-

      - name: üì¶ Install dependencies
        run: bun install --frozen-lockfile

      # @link https://github.com/changesets/action
      - name: ü¶ã Create Release Pull Request or Publish
        id: changesets
        uses: changesets/action@v1
        with:
          cwd: ${{ github.workspace }}
          title: '[Release] Version packages'
          publish: bun release
        env:
          # See https://github.com/changesets/action/issues/147
          HOME: ${{ github.workspace }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
