name: Sync Templates

on:
  push:
    branches:
      - main
    paths:
      - '.github/actions/**'
      - '.github/workflows/sync-templates.yml'
      - 'tooling/scripts/push-template.sh'
      - 'templates/**'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        template:
          - plate-template
          - plate-playground-template
    defaults:
      run:
        working-directory: templates/${{ matrix.template }}

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - uses: oven-sh/setup-bun@v2
        name: Install bun
        with:
          bun-version: latest

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - uses: actions/cache@v4
        name: â™»ï¸ Setup bun cache
        with:
          path: ~/.bun/install/cache
          key: ${{ runner.os }}-bun-${{ hashFiles('**/bun.lock') }}
          restore-keys: |
            ${{ runner.os }}-bun-

      - name: ğŸ“¥ Install
        run: bun install --frozen-lockfile

      - name: ğŸ— Build
        run: bun run build

  sync:
    needs: build
    runs-on: ubuntu-latest
    if: ${{ success() }}
    strategy:
      fail-fast: false
      matrix:
        template:
          - plate-template
          - plate-playground-template

    steps:
      - uses: actions/checkout@v4

      - name: ğŸ”„ Sync Templates
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        run: ./tooling/scripts/push-template.sh "templates/${{ matrix.template }}"
        shell: bash
