name: Templates

on:
  push:
    branches:
      - main
    paths:
      - '.github/actions/**'
      - '.github/workflows/sync-templates.yml'
      - 'scripts/sync-templates.sh'
      - 'templates/**'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        template:
          - plate-template
          - plate-playground-template
    defaults:
      run:
        working-directory: templates/${{ matrix.template }}

    steps:
      - uses: actions/checkout@v4

      - name: ğŸ“¦ Install pnpm
      - uses: pnpm/action-setup@4
        name: Install pnpm
        with:
          version: 9.15.1
          run_install: false

      - name: â™»ï¸ Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'

      - name: ğŸ“¥ Install dependencies
        run: pnpm install -r

      - name: ğŸ— Build
        run: pnpm build

  sync:
    needs: build
    runs-on: ubuntu-latest
    if: ${{ success() }}
    strategy:
      fail-fast: false
      matrix:
        template:
          - plate-template
          - plate-playground-template

    steps:
      - uses: actions/checkout@v4

      - name: ğŸ”„ Sync Templates
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        run: ./scripts/sync-templates.sh "templates/${{ matrix.template }}"
        shell: bash
